---
triple:          'arm64-apple-darwin'
binary-path:     app
relocations:
  - { offset: 0x521B, size: 0x8, addend: 0x0, symName: __ZStL8__ioinit, symObjAddr: 0x293EA, symBinAddr: 0x100008000, symSize: 0x0 }
  - { offset: 0x55BE, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x928, symBinAddr: 0x100003590, symSize: 0x18 }
  - { offset: 0x55DC, size: 0x8, addend: 0x0, symName: __Z4testv, symObjAddr: 0x258, symBinAddr: 0x100002EC0, symSize: 0x6D0 }
  - { offset: 0x56C6, size: 0x8, addend: 0x0, symName: __Z8getArrayP5CAngl, symObjAddr: 0x160, symBinAddr: 0x100002DC8, symSize: 0xF8 }
  - { offset: 0x5724, size: 0x8, addend: 0x0, symName: __Z8getArrayP5CVect, symObjAddr: 0x0, symBinAddr: 0x100002C68, symSize: 0x160 }
  - { offset: 0x9338, size: 0x8, addend: 0x0, symName: __ZStL8__ioinit, symObjAddr: 0x28817, symBinAddr: 0x100008001, symSize: 0x0 }
  - { offset: 0x94AA, size: 0x8, addend: 0x0, symName: __ZN5CAnglplERK5CVect, symObjAddr: 0x2F4, symBinAddr: 0x1000038EC, symSize: 0xD4 }
  - { offset: 0x9526, size: 0x8, addend: 0x0, symName: __ZN5CAnglC1Ed, symObjAddr: 0x2D0, symBinAddr: 0x1000038C8, symSize: 0x24 }
  - { offset: 0x9556, size: 0x8, addend: 0x0, symName: __ZN5CAnglC2Ed, symObjAddr: 0x2AC, symBinAddr: 0x1000038A4, symSize: 0x24 }
  - { offset: 0x959D, size: 0x8, addend: 0x0, symName: __ZN5CAnglC1Ev, symObjAddr: 0x290, symBinAddr: 0x100003888, symSize: 0x1C }
  - { offset: 0x95C5, size: 0x8, addend: 0x0, symName: __ZN5CAnglC2Ev, symObjAddr: 0x274, symBinAddr: 0x10000386C, symSize: 0x1C }
  - { offset: 0x95EC, size: 0x8, addend: 0x0, symName: __ZN5CVectmiERKS_, symObjAddr: 0x208, symBinAddr: 0x100003800, symSize: 0x6C }
  - { offset: 0x9635, size: 0x8, addend: 0x0, symName: __ZN5CVectplERK5CAngl, symObjAddr: 0x11C, symBinAddr: 0x100003714, symSize: 0xEC }
  - { offset: 0x966F, size: 0x8, addend: 0x0, symName: __ZN5CVectplERKS_, symObjAddr: 0xB0, symBinAddr: 0x1000036A8, symSize: 0x6C }
  - { offset: 0x96F7, size: 0x8, addend: 0x0, symName: __ZN5CVectC1Edd, symObjAddr: 0x7C, symBinAddr: 0x100003674, symSize: 0x34 }
  - { offset: 0x972F, size: 0x8, addend: 0x0, symName: __ZN5CVectC2Edd, symObjAddr: 0x48, symBinAddr: 0x100003640, symSize: 0x34 }
  - { offset: 0x977E, size: 0x8, addend: 0x0, symName: __ZN5CVectC1Ev, symObjAddr: 0x24, symBinAddr: 0x10000361C, symSize: 0x24 }
  - { offset: 0x97A6, size: 0x8, addend: 0x0, symName: __ZN5CVectC2Ev, symObjAddr: 0x0, symBinAddr: 0x1000035F8, symSize: 0x24 }
...
