---
triple:          'arm64-apple-darwin'
binary-path:     app
relocations:
  - { offset: 0x19, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003DCC, symSize: 0x54 }
  - { offset: 0x94B, size: 0x8, addend: 0x0, symName: __Z1fP7__sFILE, symObjAddr: 0x54, symBinAddr: 0x100003E20, symSize: 0xEC }
  - { offset: 0x9D3, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003DCC, symSize: 0x54 }
...
