---
triple:          'arm64-apple-darwin'
binary-path:     app
relocations:
  - { offset: 0x5229, size: 0x8, addend: 0x0, symName: __ZStL8__ioinit, symObjAddr: 0x15DB3, symBinAddr: 0x100008000, symSize: 0x0 }
  - { offset: 0x54B0, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x1000007EC, symSize: 0x38 }
  - { offset: 0x90F0, size: 0x8, addend: 0x0, symName: __ZStL8__ioinit, symObjAddr: 0x18107, symBinAddr: 0x100008001, symSize: 0x0 }
  - { offset: 0x9533, size: 0x8, addend: 0x0, symName: __Z4funcv, symObjAddr: 0x0, symBinAddr: 0x100000874, symSize: 0xCD4 }
  - { offset: 0xCCDC, size: 0x8, addend: 0x0, symName: __Z7isdigiti, symObjAddr: 0x68, symBinAddr: 0x100001600, symSize: 0x20 }
  - { offset: 0xD4CB, size: 0x8, addend: 0x0, symName: __ZStL8__ioinit, symObjAddr: 0x1AE02, symBinAddr: 0x100008002, symSize: 0x0 }
  - { offset: 0xD74C, size: 0x8, addend: 0x0, symName: __ZNK5CIntN7getSignEv, symObjAddr: 0x1E04, symBinAddr: 0x10000339C, symSize: 0x30 }
  - { offset: 0xD778, size: 0x8, addend: 0x0, symName: __ZNK5CIntN4getNEv, symObjAddr: 0x1DEC, symBinAddr: 0x100003384, symSize: 0x18 }
  - { offset: 0xD7A4, size: 0x8, addend: 0x0, symName: __ZN5CIntN3getEbi, symObjAddr: 0x1C24, symBinAddr: 0x1000031BC, symSize: 0x1C8 }
  - { offset: 0xD812, size: 0x8, addend: 0x0, symName: __ZNK5CIntN5printEv, symObjAddr: 0x1BA8, symBinAddr: 0x100003140, symSize: 0x7C }
  - { offset: 0xD870, size: 0x8, addend: 0x0, symName: __ZNK5CIntN3negEv, symObjAddr: 0x1AC4, symBinAddr: 0x10000305C, symSize: 0xE4 }
  - { offset: 0xD8DE, size: 0x8, addend: 0x0, symName: __ZNK5CIntNmiERKS_, symObjAddr: 0x15BC, symBinAddr: 0x100002B54, symSize: 0x508 }
  - { offset: 0xD9F6, size: 0x8, addend: 0x0, symName: __ZNK5CIntNplERKS_, symObjAddr: 0x1160, symBinAddr: 0x1000026F8, symSize: 0x45C }
  - { offset: 0xDADB, size: 0x8, addend: 0x0, symName: __ZN5CIntNaSERKS_, symObjAddr: 0x1088, symBinAddr: 0x100002620, symSize: 0xD8 }
  - { offset: 0xDB36, size: 0x8, addend: 0x0, symName: __ZNK5CIntNixEi, symObjAddr: 0x1014, symBinAddr: 0x1000025AC, symSize: 0x74 }
  - { offset: 0xDB91, size: 0x8, addend: 0x0, symName: __ZN5CIntND1Ev, symObjAddr: 0xFE0, symBinAddr: 0x100002578, symSize: 0x34 }
  - { offset: 0xDBB9, size: 0x8, addend: 0x0, symName: __ZN5CIntND2Ev, symObjAddr: 0xFAC, symBinAddr: 0x100002544, symSize: 0x34 }
  - { offset: 0xDC1E, size: 0x8, addend: 0x0, symName: __ZN5CIntNC1Eii, symObjAddr: 0xD98, symBinAddr: 0x100002330, symSize: 0x214 }
  - { offset: 0xDC7F, size: 0x8, addend: 0x0, symName: __ZN5CIntNC2Eii, symObjAddr: 0xB98, symBinAddr: 0x100002130, symSize: 0x200 }
  - { offset: 0xDD1F, size: 0x8, addend: 0x0, symName: __ZN5CIntNC1ERKS_, symObjAddr: 0xAEC, symBinAddr: 0x100002084, symSize: 0xAC }
  - { offset: 0xDDA1, size: 0x8, addend: 0x0, symName: __ZN5CIntNC2ERKS_, symObjAddr: 0xA40, symBinAddr: 0x100001FD8, symSize: 0xAC }
  - { offset: 0xDEC8, size: 0x8, addend: 0x0, symName: __ZN5CIntNC1EiPKc, symObjAddr: 0x5C0, symBinAddr: 0x100001B58, symSize: 0x480 }
  - { offset: 0xE002, size: 0x8, addend: 0x0, symName: __ZN5CIntNC2EiPKc, symObjAddr: 0x140, symBinAddr: 0x1000016D8, symSize: 0x480 }
  - { offset: 0xE153, size: 0x8, addend: 0x0, symName: __ZN5CIntNC1Ev, symObjAddr: 0xE4, symBinAddr: 0x10000167C, symSize: 0x5C }
  - { offset: 0xE17B, size: 0x8, addend: 0x0, symName: __ZN5CIntNC2Ev, symObjAddr: 0x88, symBinAddr: 0x100001620, symSize: 0x5C }
  - { offset: 0xE1A6, size: 0x8, addend: 0x0, symName: __Z9__isctypeim, symObjAddr: 0x0, symBinAddr: 0x100001598, symSize: 0x68 }
...
