---
triple:          'arm64-apple-darwin'
binary-path:     app
relocations:
  - { offset: 0x19, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003B70, symSize: 0x228 }
  - { offset: 0x94C, size: 0x8, addend: 0x0, symName: __Z1fPKiiPiS1_, symObjAddr: 0x228, symBinAddr: 0x100003D98, symSize: 0xFC }
  - { offset: 0xA13, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003B70, symSize: 0x228 }
...
