---
triple:          'arm64-apple-darwin'
binary-path:     app
relocations:
  - { offset: 0x5148, size: 0x8, addend: 0x0, symName: __ZStL8__ioinit, symObjAddr: 0x16350, symBinAddr: 0x100008000, symSize: 0x0 }
  - { offset: 0x52A9, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003BB0, symSize: 0x2CC }
...
